apiVersion: v1
kind: Pod
metadata: 
  name: web-page
spec: 
  containers:
  - name: web-page
    image: cbcarlos7/web-page-britosoftware:1.0
    ports: 
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
 name: web-page-service
spec:
  type: NodePort
  selector:
    app: web-page
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
